GET http://127.0.0.1:3000/tasks

###

POST http://127.0.0.1:3000/tasks
Content-Type: application/json

{
    "title": "Task 1",
    "description": "Description 1"
}

###

PATCH http://127.0.0.1:3000/tasks/63d87522f7612218d7881535
Content-Type: application/json

{
    "completed": "true"
}

###

DELETE http://127.0.0.1:3000/tasks/63d87522f7612218d7881535
